[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args = ["-"]}

[language.config.pylsp.plugins]
flake8 = {enabled = false}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = { enabled = true, ignore = ["F401"], lineLength = 120 }
rope = { enabled = true }
pydocstyle = { enabled = true }

[language.debugger]
name = "debugpy"
transport = "tcp"
command = "python"
args = ["-m", "debugpy"]
port-arg = "-listen localhost:5678"

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "main", completion = "filename", default = "main.py" } ]
args = { program = "{0}" }
