# === LSP Configs ===
# Python
[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
language-servers = ["pylsp"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
pylint = { enabled = true }
pylsp-mypy = { enabled = true }
isort = { enabled = true, profile = "black" }
ruff = { enabled = true, ignore = ["F401"], lineLength = 120 }
black = { enabled = true, line_length = 120 }
flake8 = { enabled = false }
autopep8 = { enabled = false }
mccabe = { enabled = false }
pycodestyle = { enabled = false }
pyflakes = { enabled = false }
yapf = { enabled = false }

[language.debugger]
name = "debugpy"
transport = "tcp"
command = "python"
args = ["-m", "debugpy"]
port-arg = "-listen localhost:5678"

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "main", completion = "filename", default = "main.py" } ]
args = { program = "{0}" }

[[language.debugger.templates]]
name = "uvicorn"
request = "launch"
completion = [ { name = "module" }, { name = "filename" }, { name = "symbol" } ]
args =  { program = "uvicorn {0}.{1}:{2} --debug --reload"}

# JS/TS
# TypeScript
[[language]]
name = "typescript"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, { name = "efm", only-features = [ "diagnostics", "format" ] }]

[language-server.efm]
command = "efm-langserver"

[language-server.typescript-language-server]
# pass format options according to https://github.com/typescript-language-server/typescript-language-server#workspacedidchangeconfiguration omitting the "[language].format." prefix.
config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true } }

# Markdown
[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }

# Groovy / Java
[[language]]
name = "java"
file-types = ["java", "groovy", "Jenkinsfile", "jenkinsfile"]
