[[language]]
name = "python"
language-server = { command = "pylsp" }
auto-format = true
formatter = { command = "black", args = ["-"]}

[language.debugger]
name = "debugpy"
transport = "tcp"
command = "python"
args = ["-m", "debugpy"]
port-arg = "-listen localhost:5678"

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "main", completion = "filename", default = "main.py" } ]
args = { program = "{0}" }
